openapi: 3.0.3
info:
  title: ReEarth-CMS Integration API
  description: ReEarth-CMS Integration API
  version: 1.0.0
paths:
  ###   PROJECTS   ###
  '/{workspaceIdOrAlias}/projects':
    $ref: './project.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}':
    $ref: './project.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D'

  ###   Models   ###
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/models':
    $ref: './model.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1models'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/models/{modelIdOrKey}':
    $ref: './model.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1models~1%7BmodelIdOrKey%7D'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/models/{modelIdOrKey}/schema.json':
    $ref: './model.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1models~1%7BmodelIdOrKey%7D~1schema.json'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/models/{modelIdOrKey}/metadata_schema.json':
    $ref: './model.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1models~1%7BmodelIdOrKey%7D~1metadata_schema.json'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/models/{modelIdOrKey}/import':
    $ref: './model.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1models~1%7BmodelIdOrKey%7D~1import'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/models/{modelIdOrKey}/copy':
    $ref: './model.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1models~1%7BmodelIdOrKey%7D~1copy'

  ###   GROUPS   ###
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/groups':
    $ref: './group.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1groups'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/groups/{groupIdOrKey}':
    $ref: './group.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1groups~1%7BgroupIdOrKey%7D'

  ###   SCHEMATA   ###
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/schemata/{schemaId}/fields':
    $ref: './field.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1schemata~1%7BschemaId%7D~1fields'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/schemata/{schemaId}/fields/{fieldIdOrKey}':
    $ref: './field.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1schemata~1%7BschemaId%7D~1fields~1%7BfieldIdOrKey%7D'

  ###   ITEMS   ###
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/models/{modelIdOrKey}/items':
    $ref: './item.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1models~1%7BmodelIdOrKey%7D~1items'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/models/{modelIdOrKey}/items/filter':
    $ref: './item.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1models~1%7BmodelIdOrKey%7D~1items~1filter'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/models/{modelIdOrKey}/items.geojson':
    $ref: './item.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1models~1%7BmodelIdOrKey%7D~1items.geojson'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/models/{modelIdOrKey}/items.csv':
    $ref: './item.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1models~1%7BmodelIdOrKey%7D~1items.csv'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/models/{modelIdOrKey}/items/{itemId}':
    $ref: './item.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1models~1%7BmodelIdOrKey%7D~1items~1%7BitemId%7D'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/models/{modelIdOrKey}/items/{itemId}/publish':
    $ref: './item.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1models~1%7BmodelIdOrKey%7D~1items~1%7BitemId%7D~1publish'

  ### ITEM COMMENTS ###
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/models/{modelIdOrKey}/items/{itemId}/comments':
    $ref: './item_comment.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1models~1%7BmodelIdOrKey%7D~1items~1%7BitemId%7D~1comments'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/models/{modelIdOrKey}/items/{itemId}/comments/{commentId}':
    $ref: './item_comment.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1models~1%7BmodelIdOrKey%7D~1items~1%7BitemId%7D~1comments~1%7BcommentId%7D'

  ###   ASSETS   ###
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/assets':
    $ref: './asset.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1assets'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/assets/uploads':
    $ref: './asset.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1assets~1uploads'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/assets/{assetId}':
    $ref: './asset.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1assets~1%7BassetId%7D'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/assets/{assetId}/publish':
    $ref: './asset.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1assets~1%7BassetId%7D~1publish'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/assets/{assetId}/unpublish':
    $ref: './asset.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1assets~1%7BassetId%7D~1unpublish'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/assets/{uuid1}/{uuid2}/{filename}':
    $ref: './asset.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1assets~1%7Buuid1%7D~1%7Buuid2%7D~1%7Bfilename%7D'

  ### ASSET COMMENTS ###
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/assets/{assetId}/comments':
    $ref: './asset_comment.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1assets~1%7BassetId%7D~1comments'
  '/{workspaceIdOrAlias}/projects/{projectIdOrAlias}/assets/{assetId}/comments/{commentId}':
    $ref: './asset_comment.yml#/paths/~1%7BworkspaceIdOrAlias%7D~1projects~1%7BprojectIdOrAlias%7D~1assets~1%7BassetId%7D~1comments~1%7BcommentId%7D'

components:
  parameters:
    workspaceIdOrAliasParam:
      $ref: './_shared.yml#/components/parameters/workspaceIdOrAliasParam'
    projectIdOrAliasParam:
      $ref: './_shared.yml#/components/parameters/projectIdOrAliasParam'
    schemaIdParam:
      $ref: './_shared.yml#/components/parameters/schemaIdParam'
    modelIdOrKeyParam:
      $ref: './_shared.yml#/components/parameters/modelIdOrKeyParam'
    groupIdOrKeyParam:
      $ref: './_shared.yml#/components/parameters/groupIdOrKeyParam'
    fieldIdOrKeyParam:
      $ref: './_shared.yml#/components/parameters/fieldIdOrKeyParam'
    itemIdParam:
      $ref: './_shared.yml#/components/parameters/itemIdParam'
    assetIdParam:
      $ref: './_shared.yml#/components/parameters/assetIdParam'
    commentIdParam:
      $ref: './_shared.yml#/components/parameters/commentIdParam'
    sortParam:
      $ref: './_shared.yml#/components/parameters/sortParam'
    sortDirParam:
      $ref: './_shared.yml#/components/parameters/sortDirParam'
    pageParam:
      $ref: './_shared.yml#/components/parameters/pageParam'
    perPageParam:
      $ref: './_shared.yml#/components/parameters/perPageParam'
    refParam:
      $ref: './_shared.yml#/components/parameters/refParam'
    assetParam:
      $ref: './_shared.yml#/components/parameters/assetParam'
    keywordParam:
      $ref: './_shared.yml#/components/parameters/keywordParam'
  schemas:
    project:
      $ref: './project.yml#/components/schemas/project'
    publicationSettings:
      $ref: './project.yml#/components/schemas/publicationSettings'
    apiKey:
      $ref: './project.yml#/components/schemas/apiKey'
    accessibility:
      $ref: './project.yml#/components/schemas/accessibility'
    projectRequestRole:
      $ref: './project.yml#/components/schemas/projectRequestRole'
    model:
      $ref: './model.yml#/components/schemas/model'
    JSONSchema:
      $ref: './model.yml#/components/schemas/JSONSchema'
    group:
      $ref: './group.yml#/components/schemas/group'
    schema:
      $ref: './field.yml#/components/schemas/schema'
    schemaField:
      $ref: './field.yml#/components/schemas/schemaField'
    valueType:
      $ref: './field.yml#/components/schemas/valueType'
    tagResponse:
      $ref: './field.yml#/components/schemas/tagResponse'
    item:
      $ref: './item.yml#/components/schemas/item'
    versionedItem:
      $ref: './item.yml#/components/schemas/versionedItem'
    version:
      $ref: './item.yml#/components/schemas/version'
    field:
      $ref: './item.yml#/components/schemas/field'
    fieldSelector:
      $ref: './item.yml#/components/schemas/fieldSelector'
    condition:
      $ref: './item.yml#/components/schemas/condition'
    assetEmbedding:
      $ref: './_shared.yml#/components/schemas/assetEmbedding'
    GeoJSON:
      $ref: './item.yml#/components/schemas/GeoJSON'
    refOrVersion:
      $ref: './item.yml#/components/schemas/refOrVersion'
    asset:
      $ref: './asset.yml#/components/schemas/asset'
    file:
      $ref: './asset.yml#/components/schemas/file'
    comment:
      $ref: './_shared.yml#/components/schemas/comment'
  responses:
    UnauthorizedError:
      $ref: './_shared.yml#/components/responses/UnauthorizedError'
    NotFoundError:
      $ref: './_shared.yml#/components/responses/NotFoundError'
  securitySchemes:
    bearerAuth:
      $ref: './_shared.yml#/components/securitySchemes/bearerAuth'
