package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"

	"github.com/reearth/reearth-cms/server/internal/adapter/gql/gqlmodel"
	"github.com/reearth/reearth-cms/server/internal/usecase/interfaces"
	"github.com/reearth/reearthx/account/accountdomain"
)

// UpdateWorkspaceSettings is the resolver for the updateWorkspaceSettings field.
func (r *mutationResolver) UpdateWorkspaceSettings(ctx context.Context, input gqlmodel.UpdateWorkspaceSettingsInput) (*gqlmodel.UpdateWorkspaceSettingsPayload, error) {
	wid, err := gqlmodel.ToID[accountdomain.Workspace](input.ID)
	if err != nil {
		return nil, err
	}

	res, err := usecases(ctx).WorkspaceSettings.UpdateOrCreate(ctx, interfaces.UpdateOrCreateWorkspaceSettingsParam{
		ID:       wid,
		Tiles:    gqlmodel.FromResourceList(input.Tiles),
		Terrains: gqlmodel.FromResourceList(input.Terrains),
	}, getOperator(ctx))
	if err != nil {
		return nil, err
	}

	return &gqlmodel.UpdateWorkspaceSettingsPayload{WorkspaceSettings: gqlmodel.ToWorkspaceSettings(res)}, nil
}
