package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/reearth/reearth-cms/server/internal/adapter/gql/gqlmodel"
	"github.com/reearth/reearth-cms/server/pkg/id"
	"github.com/reearth/reearth-cms/server/pkg/job"
	"github.com/samber/lo"
)

// CancelJob is the resolver for the cancelJob field.
func (r *mutationResolver) CancelJob(ctx context.Context, jobID gqlmodel.ID) (*gqlmodel.Job, error) {
	jid, err := gqlmodel.ToID[id.Job](jobID)
	if err != nil {
		return nil, err
	}

	j, err := usecases(ctx).Job.Cancel(ctx, jid, getOperator(ctx))
	if err != nil {
		return nil, err
	}

	return gqlmodel.ToJob(j), nil
}

// Job is the resolver for the job field.
func (r *queryResolver) Job(ctx context.Context, jobID gqlmodel.ID) (*gqlmodel.Job, error) {
	jid, err := gqlmodel.ToID[id.Job](jobID)
	if err != nil {
		return nil, err
	}

	j, err := usecases(ctx).Job.FindByID(ctx, jid, getOperator(ctx))
	if err != nil {
		return nil, err
	}

	return gqlmodel.ToJob(j), nil
}

// Jobs is the resolver for the jobs field.
func (r *queryResolver) Jobs(ctx context.Context, projectID gqlmodel.ID, typeArg *gqlmodel.JobType, status *gqlmodel.JobStatus) ([]*gqlmodel.Job, error) {
	pid, err := gqlmodel.ToID[id.Project](projectID)
	if err != nil {
		return nil, err
	}

	jobs, err := usecases(ctx).Job.FindByProject(ctx, pid, gqlmodel.FromJobType(typeArg), gqlmodel.FromJobStatus(status), getOperator(ctx))
	if err != nil {
		return nil, err
	}

	return lo.Map(jobs, func(j *job.Job, _ int) *gqlmodel.Job {
		return gqlmodel.ToJob(j)
	}), nil
}

// JobProgress is the resolver for the jobProgress field.
func (r *subscriptionResolver) JobProgress(ctx context.Context, jobID gqlmodel.ID) (<-chan *gqlmodel.JobProgress, error) {
	jid, err := gqlmodel.ToID[id.Job](jobID)
	if err != nil {
		return nil, err
	}

	progressCh, err := usecases(ctx).Job.Subscribe(ctx, jid, getOperator(ctx))
	if err != nil {
		return nil, err
	}

	// Create output channel that converts job.Progress to gqlmodel.JobProgress
	out := make(chan *gqlmodel.JobProgress, 10)

	go func() {
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case progress, ok := <-progressCh:
				if !ok {
					return
				}
				out <- gqlmodel.ToJobProgress(progress)
			}
		}
	}()

	return out, nil
}
