version: 3

project:
  name: reearth-cms
  team: reearth
  policy: default

targets:
  only:
    - type: yarn
      path: web

analyze:
  modules:
    - path: web
      type: yarn
      target: .

policy:
  ignore:
    # Outdated version of eslint-plugin-storybook
    - dependency: "eslint-plugin-storybook"
      issue: "OUTDATED"
      reason: "We are aware of the outdated version and plan to upgrade after Storybook migration."

    # License issues with zip.js
    - dependency: "@zip.js/zip.js"
      issue: "GPL-1.0-only"
      reason: "License reviewed and approved internally (legal approval 2025-10-15)."
    - dependency: "@zip.js/zip.js"
      issue: "GPL-2.0-only"
      reason: "License reviewed and approved internally (legal approval 2025-10-15)."

    # License issue with ol
    - dependency: "ol"
      issue: "gpl-2.0-plus-geoserver"
      reason: "GPL license verified and acceptable for our usage (legal approval 2025-10-15)."
