import {
  HomeOutlined,
  DownloadOutlined,
  ApiOutlined,
  SearchOutlined,
  SettingOutlined,
  UsergroupAddOutlined,
  UserSwitchOutlined,
  CaretDownOutlined,
  LogoutOutlined,
  UserOutlined,
  DashboardOutlined,
  FileOutlined,
  PullRequestOutlined,
  SendOutlined,
  TableOutlined,
  UnorderedListOutlined,
  EditOutlined,
  EllipsisOutlined,
  PlusOutlined,
  CloseOutlined,
  ExclamationCircleOutlined,
  UploadOutlined,
  MessageOutlined,
  InboxOutlined,
  FullscreenOutlined,
  MoreOutlined,
  MinusCircleOutlined,
  DeleteOutlined,
  ArrowLeftOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  FolderOutlined,
  LinkOutlined,
  UserAddOutlined,
  ClearOutlined,
  CloseCircleFilled,
  ArrowUpOutlined,
  ArrowDownOutlined,
  CheckCircleFilled,
  CheckOutlined,
} from "@ant-design/icons";

import ArrowSquareOut from "./Icons/arrowSquareOut.svg";
import Asset from "./Icons/asset.svg";
import Dot from "./Icons/dot.svg";
import Key from "./Icons/key.svg";
import Link from "./Icons/link.svg";
import UnlinkSolid from "./Icons/linkSlashSolid.svg";
import LinkSolid from "./Icons/linkSolid.svg";
import ListBullets from "./Icons/listBullets.svg";
import MarkDown from "./Icons/markDown.svg";
import MyIntegrations from "./Icons/myintegrations.svg";
import NumberNine from "./Icons/numberNine.svg";
import TextAlignLeft from "./Icons/textAlignLeft.svg";
import Text from "./Icons/textT.svg";

export default {
  home: HomeOutlined,
  download: DownloadOutlined,
  api: ApiOutlined,
  search: SearchOutlined,
  settings: SettingOutlined,
  userGroupAdd: UsergroupAddOutlined,
  userSwitch: UserSwitchOutlined,
  caretDown: CaretDownOutlined,
  logout: LogoutOutlined,
  user: UserOutlined,
  dashboard: DashboardOutlined,
  file: FileOutlined,
  pullRequest: PullRequestOutlined,
  send: SendOutlined,
  table: TableOutlined,
  unorderedList: UnorderedListOutlined,
  edit: EditOutlined,
  ellipsis: EllipsisOutlined,
  plus: PlusOutlined,
  close: CloseOutlined,
  exclamationCircle: ExclamationCircleOutlined,
  upload: UploadOutlined,
  message: MessageOutlined,
  inbox: InboxOutlined,
  fullscreen: FullscreenOutlined,
  textT: Text,
  textAlignLeft: TextAlignLeft,
  markdown: MarkDown,
  asset: Asset,
  listBullets: ListBullets,
  numberNine: NumberNine,
  link: Link,
  linkSolid: LinkSolid,
  unlinkSolid: UnlinkSolid,
  LinkOutlined: LinkOutlined,
  more: MoreOutlined,
  minusCircle: MinusCircleOutlined,
  delete: DeleteOutlined,
  arrowLeft: ArrowLeftOutlined,
  myIntegrations: MyIntegrations,
  key: Key,
  panelToggleLeft: MenuFoldOutlined,
  panelToggleRight: MenuUnfoldOutlined,
  folder: FolderOutlined,
  dot: Dot,
  userAdd: UserAddOutlined,
  clear: ClearOutlined,
  closeCircle: CloseCircleFilled,
  arrowUp: ArrowUpOutlined,
  arrowDown: ArrowDownOutlined,
  arrowSquareOut: ArrowSquareOut,
  checkCircle: CheckCircleFilled,
  check: CheckOutlined,
};
