import {
  HomeOutlined,
  DownloadOutlined,
  ApiOutlined,
  SearchOutlined,
  SettingOutlined,
  UsergroupAddOutlined,
  UserSwitchOutlined,
  CaretDownOutlined,
  LogoutOutlined,
  UserOutlined,
  DashboardOutlined,
  FileOutlined,
  PullRequestOutlined,
  SendOutlined,
  TableOutlined,
  UnorderedListOutlined,
  EditOutlined,
  EllipsisOutlined,
  PlusOutlined,
  CloseOutlined,
  ExclamationCircleOutlined,
} from "@ant-design/icons";

export default {
  home: HomeOutlined,
  download: DownloadOutlined,
  api: ApiOutlined,
  search: SearchOutlined,
  settings: SettingOutlined,
  userGroupAdd: UsergroupAddOutlined,
  userSwitch: UserSwitchOutlined,
  caretDown: CaretDownOutlined,
  logout: LogoutOutlined,
  user: UserOutlined,
  dashboard: DashboardOutlined,
  file: FileOutlined,
  pullRequest: PullRequestOutlined,
  send: SendOutlined,
  table: TableOutlined,
  unorderedList: UnorderedListOutlined,
  edit: EditOutlined,
  ellipsis: EllipsisOutlined,
  plus: PlusOutlined,
  close: CloseOutlined,
  exclamationCircle: ExclamationCircleOutlined,
};
