import { render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, test, vi } from "vitest";

import { SchemaFieldType } from "@reearth-cms/components/molecules/Schema/types";
import { t } from "@reearth-cms/i18n";
import { DATA_TEST_ID } from "@reearth-cms/test/utils";

import { ImportFieldInput } from "../types";

import SchemaPreviewStep, { type Props } from "./SchemaPreviewStep";

const user = userEvent.setup();

const createMockField = (overrides: Partial<ImportFieldInput> = {}): ImportFieldInput => ({
  type: SchemaFieldType.Text,
  title: "Test Field",
  key: "test-field",
  description: "",
  multiple: false,
  unique: false,
  required: false,
  isTitle: false,
  typeProperty: {},
  hidden: false,
  ...overrides,
});

const createFieldTypeOption = (type: string, label: string) => ({
  value: type,
  label: <span data-testid={`field-type-${type}`}>{label}</span>,
});

const buildProps = (overrides: Partial<Props> = {}): Props => ({
  fields: [
    createMockField({ key: "field-1", title: "Field 1", type: SchemaFieldType.Text }),
    createMockField({ key: "field-2", title: "Field 2", type: SchemaFieldType.Integer }),
    createMockField({ key: "field-3", title: "Field 3", type: SchemaFieldType.Bool }),
  ],
  fieldTypeOptions: [
    createFieldTypeOption(SchemaFieldType.Text, "Text"),
    createFieldTypeOption(SchemaFieldType.Integer, "Integer"),
    createFieldTypeOption(SchemaFieldType.Bool, "Boolean"),
  ],
  onDragEnd: vi.fn(),
  onToggleFieldHide: vi.fn(),
  onToggleAllFieldsHide: vi.fn(),
  hasUpdateRight: true,
  hasDeleteRight: true,
  ...overrides,
});

describe("SchemaPreviewStep", () => {
  test("renders component with header and description", () => {
    render(<SchemaPreviewStep {...buildProps()} />);

    expect(screen.getByTestId(DATA_TEST_ID.SchemaPreviewStep__Wrapper)).toBeInTheDocument();
    expect(screen.getByText(t("Schema preview"))).toBeInTheDocument();
    expect(
      screen.getByText(
        t(
          "Here is the schema generated by your file. Please confirm the type of each field. If it does not match your expectations, you can modify the field type.",
        ),
      ),
    ).toBeInTheDocument();
  });

  test("renders column headers", () => {
    render(<SchemaPreviewStep {...buildProps()} />);

    expect(screen.getByText(t("Field Name"))).toBeInTheDocument();
    expect(screen.getByText(t("Field Type"))).toBeInTheDocument();
  });

  test("renders all fields in the list", () => {
    render(<SchemaPreviewStep {...buildProps()} />);

    expect(
      screen.getByTestId(DATA_TEST_ID.SchemaPreviewStep__PreviewFieldList),
    ).toBeInTheDocument();
    expect(screen.getByText("Field 1")).toBeInTheDocument();
    expect(screen.getByText("Field 2")).toBeInTheDocument();
    expect(screen.getByText("Field 3")).toBeInTheDocument();
  });

  test("renders field keys with required prefix", () => {
    render(<SchemaPreviewStep {...buildProps()} />);

    expect(screen.getByText("#field-1")).toBeInTheDocument();
    expect(screen.getByText("#field-2")).toBeInTheDocument();
    expect(screen.getByText("#field-3")).toBeInTheDocument();
  });

  test("renders field type labels", () => {
    render(<SchemaPreviewStep {...buildProps()} />);

    expect(screen.getByTestId("field-type-Text")).toBeInTheDocument();
    expect(screen.getByTestId("field-type-Integer")).toBeInTheDocument();
    expect(screen.getByTestId("field-type-Bool")).toBeInTheDocument();
  });

  test("renders required indicator for required fields", () => {
    const props = buildProps({
      fields: [createMockField({ key: "required-field", title: "Required Field", required: true })],
    });
    render(<SchemaPreviewStep {...props} />);

    const fieldList = screen.getByTestId(DATA_TEST_ID.SchemaPreviewStep__PreviewFieldList);
    expect(within(fieldList).getByText("*")).toBeInTheDocument();
  });

  test("renders unique indicator for unique fields", () => {
    const props = buildProps({
      fields: [createMockField({ key: "unique-field", title: "Unique Field", unique: true })],
    });
    render(<SchemaPreviewStep {...props} />);

    expect(screen.getByText(`(${t("unique")})`)).toBeInTheDocument();
  });

  test("renders title tag for title fields", () => {
    const props = buildProps({
      fields: [createMockField({ key: "title-field", title: "Title Field", isTitle: true })],
    });
    render(<SchemaPreviewStep {...props} />);

    expect(screen.getByText(t("Title"))).toBeInTheDocument();
  });

  test("calls onToggleFieldHide when field checkbox is clicked", async () => {
    const props = buildProps();
    render(<SchemaPreviewStep {...props} />);

    const checkboxes = screen.getAllByTestId(DATA_TEST_ID.SchemaPreviewStep__PreviewSkipCheckbox);
    await user.click(checkboxes[0]);

    expect(props.onToggleFieldHide).toHaveBeenCalledWith("field-1");
  });

  test("calls onToggleAllFieldsHide when header checkbox is clicked", async () => {
    const props = buildProps();
    render(<SchemaPreviewStep {...props} />);

    const headerCheckbox = screen.getByTestId(
      DATA_TEST_ID.SchemaPreviewStep__PreviewSkipAllCheckbox,
    );
    expect(headerCheckbox).toBeInTheDocument();

    if (headerCheckbox) {
      await user.click(headerCheckbox);
      expect(props.onToggleAllFieldsHide).toHaveBeenCalled();
    }
  });

  test("shows all checkboxes as checked when no fields are hidden", () => {
    const props = buildProps({
      fields: [
        createMockField({ key: "field-1", hidden: false }),
        createMockField({ key: "field-2", hidden: false }),
      ],
    });
    render(<SchemaPreviewStep {...props} />);

    const checkboxes = screen.getAllByTestId(DATA_TEST_ID.SchemaPreviewStep__PreviewSkipCheckbox);
    checkboxes.forEach(checkbox => {
      expect(checkbox).toBeChecked();
    });
  });

  test("shows checkbox as unchecked when field is hidden", () => {
    const props = buildProps({
      fields: [
        createMockField({ key: "field-1", hidden: true }),
        createMockField({ key: "field-2", hidden: false }),
      ],
    });
    render(<SchemaPreviewStep {...props} />);

    const checkboxes = screen.getAllByTestId(DATA_TEST_ID.SchemaPreviewStep__PreviewSkipCheckbox);
    expect(checkboxes[0]).not.toBeChecked();
    expect(checkboxes[1]).toBeChecked();
  });

  test("renders drag icon when hasUpdateRight is true", () => {
    const props = buildProps({ hasUpdateRight: true });
    render(<SchemaPreviewStep {...props} />);

    const fieldList = screen.getByTestId(DATA_TEST_ID.SchemaPreviewStep__PreviewFieldList);
    const dragIcons = within(fieldList).getAllByRole("img");
    expect(dragIcons.length).toBeGreaterThan(0);
  });

  test("does not render drag icon when hasUpdateRight is false", () => {
    const props = buildProps({ hasUpdateRight: false });
    render(<SchemaPreviewStep {...props} />);

    const fieldList = screen.getByTestId(DATA_TEST_ID.SchemaPreviewStep__PreviewFieldList);
    const grabbableElements = fieldList.querySelectorAll(".grabbable");
    expect(grabbableElements).toHaveLength(0);
  });

  test("disables field checkbox when hasDeleteRight is false", () => {
    const props = buildProps({ hasDeleteRight: false });
    render(<SchemaPreviewStep {...props} />);

    const checkboxButtons = screen
      .getAllByTestId(DATA_TEST_ID.SchemaPreviewStep__PreviewSkipCheckbox)
      .map(checkbox => checkbox.closest("button"));

    checkboxButtons.forEach(button => {
      expect(button).toBeDisabled();
    });
  });

  test("renders empty list when no fields provided", () => {
    const props = buildProps({ fields: [] });
    render(<SchemaPreviewStep {...props} />);

    expect(
      screen.getByTestId(DATA_TEST_ID.SchemaPreviewStep__PreviewFieldList),
    ).toBeInTheDocument();
    expect(
      screen.queryByTestId(DATA_TEST_ID.SchemaPreviewStep__PreviewSkipCheckbox),
    ).not.toBeInTheDocument();
  });

  test("handles unknown field type gracefully", () => {
    const props = buildProps({
      fields: [
        createMockField({
          key: "unknown-field",
          title: "Unknown Type Field",
          type: "UnknownType" as SchemaFieldType,
        }),
      ],
      fieldTypeOptions: [createFieldTypeOption(SchemaFieldType.Text, "Text")],
    });
    render(<SchemaPreviewStep {...props} />);

    expect(screen.getByText("Unknown Type Field")).toBeInTheDocument();
    expect(screen.queryByTestId("field-type-UnknownType")).not.toBeInTheDocument();
  });
});
