import styled from "@emotion/styled";
import { useMemo } from "react";
import ReactDragListView from "react-drag-listview";

import Button from "@reearth-cms/components/atoms/Button";
import Checkbox from "@reearth-cms/components/atoms/Checkbox";
import Col from "@reearth-cms/components/atoms/Col";
import Icon from "@reearth-cms/components/atoms/Icon";
import List from "@reearth-cms/components/atoms/List";
import Row from "@reearth-cms/components/atoms/Row";
import Tag from "@reearth-cms/components/atoms/Tag";
import Tooltip from "@reearth-cms/components/atoms/Tooltip";
import Typography from "@reearth-cms/components/atoms/Typography";
import { useT } from "@reearth-cms/i18n";
import { DATA_TEST_ID } from "@reearth-cms/test/utils";

import { ImportFieldInput } from "../types";

export type Props = {
  fields: ImportFieldInput[];
  fieldTypeOptions: { value: string; label: JSX.Element }[];
  onDragEnd: (fromIndex: number, toIndex: number) => void;
  onToggleFieldHide: (id: string) => void;
  onToggleAllFieldsHide: () => void;
  hasUpdateRight: boolean;
  hasDeleteRight: boolean;
};

const SchemaPreviewStep: React.FC<Props> = ({
  fields,
  fieldTypeOptions,
  onDragEnd,
  onToggleFieldHide,
  onToggleAllFieldsHide,
  hasUpdateRight,
  hasDeleteRight,
}) => {
  const t = useT();

  const fieldLabel = (field: ImportFieldInput) => {
    const findField = fieldTypeOptions.find(_field => _field.value === field.type);

    return findField ? findField.label : null;
  };

  const isAllChecked = useMemo(() => fields.every(field => !field.hidden), [fields]);
  const indeterminate = useMemo(() => {
    const checkedCount = fields.filter(field => !field.hidden).length;
    return checkedCount >= 0 && checkedCount < fields.length;
  }, [fields]);

  return (
    <SchemaPreviewStepWrapper data-testid={DATA_TEST_ID.SchemaPreviewStep__Wrapper}>
      <Section>
        <SectionTitle>{t("Schema preview")}</SectionTitle>
        <Description>
          {t(
            "Here is the schema generated by your file. Please confirm the type of each field. If it does not match your expectations, you can modify the field type.",
          )}
        </Description>
        <HeaderRow>
          <Col span={1} />
          <HeaderCol span={11}>
            <span>{t("Field Name")}</span>
          </HeaderCol>
          <HeaderCol span={11}>
            <span>{t("Field Type")}</span>
          </HeaderCol>
          <Col span={1}>
            <Checkbox
              data-testid={DATA_TEST_ID.SchemaPreviewStep__PreviewSkipAllCheckbox}
              checked={isAllChecked}
              indeterminate={indeterminate}
              onClick={onToggleAllFieldsHide}
            />
          </Col>
        </HeaderRow>
      </Section>

      <ReactDragListView
        nodeSelector=".ant-list-item"
        handleSelector=".grabbable"
        lineClassName="dragLine"
        onDragEnd={onDragEnd}>
        <FieldStyledList
          data-testid={DATA_TEST_ID.SchemaPreviewStep__PreviewFieldList}
          itemLayout="horizontal">
          {fields?.map((field, _index) => (
            <StyledListItem className="draggable-item" key={field.key} noImport={field.hidden}>
              <List.Item.Meta
                title={
                  <Row>
                    <VerticalCenterCol span={1}>
                      <FieldThumbnail>
                        {hasUpdateRight && <DragIcon icon="menu" className="grabbable" />}
                      </FieldThumbnail>
                    </VerticalCenterCol>
                    <AlignLeftCol span={11}>
                      <Tooltip title={`${field.title} ${field.required ? " *" : ""} #${field.key}`}>
                        <Typography.Text ellipsis>
                          <ItemTitleHeading>{field.title}</ItemTitleHeading>
                          {field.required ? " *" : ""}
                          <ItemKey>#{field.key}</ItemKey>
                          {field.unique ? <ItemUnique>({t("unique")})</ItemUnique> : ""}
                          {field.isTitle ? <ItemTitleTag>{t("Title")}</ItemTitleTag> : ""}
                        </Typography.Text>
                      </Tooltip>
                    </AlignLeftCol>
                    <AlignLeftCol span={11}>{fieldLabel(field)}</AlignLeftCol>
                    <VerticalCenterCol span={1}>
                      <Button
                        type="text"
                        shape="circle"
                        size="small"
                        onClick={() => onToggleFieldHide(field.key)}
                        icon={
                          <Tooltip title={field.hidden ? t("Not import") : t("Import")}>
                            <Checkbox
                              checked={!field.hidden}
                              data-testid={DATA_TEST_ID.SchemaPreviewStep__PreviewSkipCheckbox}
                            />
                          </Tooltip>
                        }
                        disabled={!hasDeleteRight}
                      />
                    </VerticalCenterCol>
                  </Row>
                }
              />
            </StyledListItem>
          ))}
        </FieldStyledList>
      </ReactDragListView>
    </SchemaPreviewStepWrapper>
  );
};

// const ItemTitleHeading = (props: { field: ImportFieldInput }) => (
//   <Tooltip title={props.field.title}>
//     <StyledTitleHeading>{props.field.title}</StyledTitleHeading>
//   </Tooltip>
// );
//
// const ItemKey = (props: { field: ImportFieldInput }) => {
//   const key = `#${props.field.key}`;
//   return (
//     <Tooltip title={key}>
//       <StyledItemKey>{key}</StyledItemKey>
//     </Tooltip>
//   );
// };

export default SchemaPreviewStep;

const SchemaPreviewStepWrapper = styled.div`
  height: 100%;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
`;

const Section = styled.div`
  padding-top: 24px;
  padding-bottom: 12px;
  position: sticky;
  top: 0;
  z-index: 10;
  background: #ffffff;
`;

const SectionTitle = styled.h3``;

const Description = styled.p`
  color: rgba(0, 0, 0, 0.45);
`;

const HeaderRow = styled(Row)`
  padding: 0 24px;
  color: rgba(0, 0, 0, 0.45);
`;

const HeaderCol = styled(Col)`
  text-align: left;
`;

const AlignLeftCol = styled(Col)`
  text-align: left;
  display: flex;
  align-items: center;
`;

const VerticalCenterCol = styled(Col)`
  display: flex;
  align-items: center;
`;

const FieldStyledList = styled(List)`
  .ant-list-empty-text {
    display: none;
  }
  .ant-list-item {
    background-color: #fff;
    padding: 12px 24px;
    .ant-list-item-meta {
      .ant-list-item-meta-content {
        text-align: center;
        margin: auto;
      }
      .ant-list-item-meta-title {
        margin: 0;
      }
      align-items: center;
    }
    .ant-list-item-action > li {
      padding: 0 3px;
    }
  }
`;

const StyledListItem = styled(List.Item)<{ noImport?: boolean }>`
  opacity: ${({ noImport: noImport = false }) => (noImport ? 0.5 : 1)};
`;

const FieldThumbnail = styled.div`
  display: flex;
  align-items: center;
  h3 {
    margin: 0;
    margin-left: 12px;
    font-weight: 400;
    font-size: 14px;
    line-height: 22px;
    color: rgba(0, 0, 0, 0.45);
  }
`;

// const ItemTitle = styled.p`
//   color: rgba(0, 0, 0, 0.85);
//   margin: 0;
//   display: flex;
//   justify-content: start;
// `;

const ItemTitleHeading = styled.span`
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
`;

const ItemKey = styled.span`
  margin-left: 4px;
  color: rgba(0, 0, 0, 0.45);
  font-weight: 400;
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
`;

const ItemUnique = styled.span`
  margin-left: 4px;
  color: rgba(0, 0, 0, 0.45);
  font-weight: 400;
`;

const ItemTitleTag = styled(Tag)`
  margin-left: 4px;
  color: rgba(0, 0, 0, 0.45);
  background-color: #fafafa;
`;

const DragIcon = styled(Icon)`
  margin-right: 16px;
  cursor: grab;
  :active {
    cursor: grabbing;
  }
`;
