// Code generated by MockGen. DO NOT EDIT.
// Source: ./authorization.go
//
// Generated by this command:
//
//	mockgen -source=./authorization.go -destination=./gatewaymock/authorization.go -package=gatewaymock
//

// Package gatewaymock is a generated GoMock package.
package gatewaymock

import (
	context "context"
	reflect "reflect"

	rbac "github.com/reearth/reearth-cms/server/pkg/rbac"
	workspace "github.com/reearth/reearthx/account/accountdomain/workspace"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthorization is a mock of Authorization interface.
type MockAuthorization struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizationMockRecorder
	isgomock struct{}
}

// MockAuthorizationMockRecorder is the mock recorder for MockAuthorization.
type MockAuthorizationMockRecorder struct {
	mock *MockAuthorization
}

// NewMockAuthorization creates a new mock instance.
func NewMockAuthorization(ctrl *gomock.Controller) *MockAuthorization {
	mock := &MockAuthorization{ctrl: ctrl}
	mock.recorder = &MockAuthorizationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorization) EXPECT() *MockAuthorizationMockRecorder {
	return m.recorder
}

// CheckPermission mocks base method.
func (m *MockAuthorization) CheckPermission(ctx context.Context, resource rbac.Resource, action rbac.Action, workspaceID ...workspace.ID) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, resource, action}
	for _, a := range workspaceID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckPermission", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPermission indicates an expected call of CheckPermission.
func (mr *MockAuthorizationMockRecorder) CheckPermission(ctx, resource, action any, workspaceID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, resource, action}, workspaceID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermission", reflect.TypeOf((*MockAuthorization)(nil).CheckPermission), varargs...)
}
