// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/reearth/reearth-cms/server/internal/usecase/gateway (interfaces: TaskRunner,PolicyChecker,Authorization)
//
// Generated by this command:
//
//	mockgen -destination=gatewaymock/gateway_gen.go -package=gatewaymock . TaskRunner,PolicyChecker,Authorization
//

// Package gatewaymock is a generated GoMock package.
package gatewaymock

import (
	context "context"
	reflect "reflect"

	gateway "github.com/reearth/reearth-cms/server/internal/usecase/gateway"
	rbac "github.com/reearth/reearth-cms/server/pkg/rbac"
	task "github.com/reearth/reearth-cms/server/pkg/task"
	workspace "github.com/reearth/reearthx/account/accountdomain/workspace"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskRunner is a mock of TaskRunner interface.
type MockTaskRunner struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRunnerMockRecorder
	isgomock struct{}
}

// MockTaskRunnerMockRecorder is the mock recorder for MockTaskRunner.
type MockTaskRunnerMockRecorder struct {
	mock *MockTaskRunner
}

// NewMockTaskRunner creates a new mock instance.
func NewMockTaskRunner(ctrl *gomock.Controller) *MockTaskRunner {
	mock := &MockTaskRunner{ctrl: ctrl}
	mock.recorder = &MockTaskRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRunner) EXPECT() *MockTaskRunnerMockRecorder {
	return m.recorder
}

// HealthCheck mocks base method.
func (m *MockTaskRunner) HealthCheck(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockTaskRunnerMockRecorder) HealthCheck(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockTaskRunner)(nil).HealthCheck), arg0)
}

// Retry mocks base method.
func (m *MockTaskRunner) Retry(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retry", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Retry indicates an expected call of Retry.
func (mr *MockTaskRunnerMockRecorder) Retry(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retry", reflect.TypeOf((*MockTaskRunner)(nil).Retry), arg0, arg1)
}

// Run mocks base method.
func (m *MockTaskRunner) Run(arg0 context.Context, arg1 task.Payload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockTaskRunnerMockRecorder) Run(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockTaskRunner)(nil).Run), arg0, arg1)
}

// MockPolicyChecker is a mock of PolicyChecker interface.
type MockPolicyChecker struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyCheckerMockRecorder
	isgomock struct{}
}

// MockPolicyCheckerMockRecorder is the mock recorder for MockPolicyChecker.
type MockPolicyCheckerMockRecorder struct {
	mock *MockPolicyChecker
}

// NewMockPolicyChecker creates a new mock instance.
func NewMockPolicyChecker(ctrl *gomock.Controller) *MockPolicyChecker {
	mock := &MockPolicyChecker{ctrl: ctrl}
	mock.recorder = &MockPolicyCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyChecker) EXPECT() *MockPolicyCheckerMockRecorder {
	return m.recorder
}

// CheckPolicy mocks base method.
func (m *MockPolicyChecker) CheckPolicy(ctx context.Context, req gateway.PolicyCheckRequest) (*gateway.PolicyCheckResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPolicy", ctx, req)
	ret0, _ := ret[0].(*gateway.PolicyCheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPolicy indicates an expected call of CheckPolicy.
func (mr *MockPolicyCheckerMockRecorder) CheckPolicy(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPolicy", reflect.TypeOf((*MockPolicyChecker)(nil).CheckPolicy), ctx, req)
}

// MockAuthorization is a mock of Authorization interface.
type MockAuthorization struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizationMockRecorder
	isgomock struct{}
}

// MockAuthorizationMockRecorder is the mock recorder for MockAuthorization.
type MockAuthorizationMockRecorder struct {
	mock *MockAuthorization
}

// NewMockAuthorization creates a new mock instance.
func NewMockAuthorization(ctrl *gomock.Controller) *MockAuthorization {
	mock := &MockAuthorization{ctrl: ctrl}
	mock.recorder = &MockAuthorizationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorization) EXPECT() *MockAuthorizationMockRecorder {
	return m.recorder
}

// CheckPermission mocks base method.
func (m *MockAuthorization) CheckPermission(ctx context.Context, resource rbac.Resource, action rbac.Action, workspaceID ...workspace.ID) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, resource, action}
	for _, a := range workspaceID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckPermission", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPermission indicates an expected call of CheckPermission.
func (mr *MockAuthorizationMockRecorder) CheckPermission(ctx, resource, action any, workspaceID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, resource, action}, workspaceID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermission", reflect.TypeOf((*MockAuthorization)(nil).CheckPermission), varargs...)
}
