name: License Check
on:
  workflow_dispatch:
  pull_request:

jobs:
  server-license-check:
    name: Server License Check
    runs-on: ubuntu-latest
    steps:
      - uses: reearth/actions/license-checker/go@9a0086b0f0118f107713b3d2708138ebfe06d5ad
        with:
          subdirectory: server
  web-license-check:
    name: Web License Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: '**/yarn.lock'
      - name: Install
        run: yarn install
      - uses: reearth/actions/license-checker/npm@e445d10332411e14f53e6abc73c966ecb49d3e57
        with:
          subdirectory: web
