name: server_deploy_test
on:
  workflow_run:
    workflows: [server_build]
    types: [completed]
    branches: [main]

env:
  IMAGE: reearth/reearth-cms:nightly
  IMAGE_NAME: us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/reearth-cms:nightly
  GCP_REGION: us_central1
jobs:
  server_deploy_test:
    name: Deploy app to dev env
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.repository.full_name == 'reearth/reearth-cms'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
      - name: Configure docker
        run: gcloud auth configure-docker --quiet
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push nightly
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./server
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: VERSION=0.0.0-SNAPSHOT-${{ needs.info.outputs.sha_short }}
          tags: ${{ env.IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy reearth-cms \
            --image $IMAGE_NAME \
            --project $GCP_PROJECT \
            --region $GCP_REGION \
            --platform managed \
            --quiet
