name: Stage
on:
  workflow_dispatch:

jobs:
  stage:
    name: Stage
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: git config
        run: |
          git config --global user.name ${{ vars.GH_APP_USER }}
          git config --global user.email ${{ vars.GH_APP_ID }}+${{ vars.GH_APP_USER }}[bot]@users.noreply.github.com
          git config --global pull.rebase false
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - name: Checkout release branch
        run: git switch release || git switch -c release
      - name: Merge main branch to release branch
        run: git merge -X theirs main
      - name: Git push
        run: git push origin release