import { type CodegenConfig } from "@graphql-codegen/cli";

const GENERATED = "generated";

// Apollo client migration guide:
// 1. https://www.apollographql.com/docs/react/migrating/apollo-client-4-migration
// 2. https://www.apollographql.com/docs/react/development-testing/graphql-codegen
const config: CodegenConfig = {
  // This assumes that all your source files are in a top-level `src/` directory - you might need to adjust this to your file structure
  documents: ["src/gql/fragments/*.ts", "src/gql/queries/*.ts", "src/**/*.graphql"],
  generates: {
    [`src/gql/__${GENERATED}__/graphql.${GENERATED}.ts`]: {
      plugins: ["typescript"],
    },
    "src/": {
      // Note: these config options moved from the other generated file config
      config: {
        avoidOptionals: {
          // Use `null` for nullable fields instead of optionals
          field: true,
          // Allow nullable input fields to remain unspecified
          inputValue: false,
        },
        // Use `unknown` instead of `any` for unconfigured scalars
        defaultScalarType: "unknown",
        // Apollo Client always includes `__typename` fields
        nonOptionalTypename: true,
        scalars: {
          Cursor: "string",
          DateTime: "Date",
          FileSize: "number",
          ID: "string",
          Lang: "string",
          TranslatedString: "{ [lang in string]?: string } | null",
          URL: "string",
        },
        // Apollo Client doesn't add the `__typename` field to root types so
        // don't generate a type for the `__typename` for root operation types.
        skipTypeNameForRoot: true,
      },
      plugins: ["typescript-operations", "typed-document-node"],
      preset: "near-operation-file",
      presetConfig: {
        // This should be the file generated by the "typescript" plugin above,
        // relative to the directory specified for this configuration
        baseTypesPath: `./gql/__${GENERATED}__/graphql.${GENERATED}.ts`,
        folder: `../__${GENERATED}__/`,
      },
    },
  },
  hooks: { afterAllFileWrite: ["prettier --write"] },
  ignoreNoDocuments: true,
  schema: "../server/schemas/**/*.graphql",
};

export default config;
